OPEN-ENT-NG/appointments

backend/src/main/java/fr/openent/appointments/core/constants/Field.java, backend/src/main/java/fr/openent/appointments/core/constants/Fields.java, backend/src/main/java/fr/openent/appointments/core/constants/SqlTables.java, backend/src/main/java/fr/openent/appointments/core/constants/WorkflowRight.java, backend/src/main/java/fr/openent/appointments/enums/Actions.java, backend/src/main/java/fr/openent/appointments/enums/Day.java, backend/src/main/java/fr/openent/appointments/enums/GridState.java, backend/src/main/java/fr/openent/appointments/enums/Periodicity.java, backend/src/main/java/fr/openent/appointments/helper/DateHelper.java, backend/src/main/java/fr/openent/appointments/helper/FutureHelper.java, backend/src/main/java/fr/openent/appointments/helper/IModelHelper.java, backend/src/main/java/fr/openent/appointments/helper/StringHelper.java, backend/src/main/java/fr/openent/appointments/helper/TransactionHelper.java, backend/src/main/java/fr/openent/appointments/model/DailySlot.java, backend/src/main/java/fr/openent/appointments/model/IModel.java, backend/src/main/java/fr/openent/appointments/model/TransactionElement.java, backend/src/main/java/fr/openent/appointments/model/bdd/Grid.java, backend/src/main/java/fr/openent/appointments/model/payload/GridPayload.java, backend/src/main/java/fr/openent/appointments/security/ManageRight.java, backend/src/main/java/fr/openent/appointments/security/ViewRight.java, backend/src/main/java/fr/openent/appointments/security/WorkflowActionUtils.java, backend/src/main/java/fr/openent/appointments/security/WorkflowActions.java
- Initialized the repository with the core components for the project.
- Added the initial data models necessary for the early development phase.
- Included utility files (helpers) to simplify and standardize common operations.
[RDV-5](https://jira.support-ent.fr/browse/RDV-5)
=> feat(init): #RDV-5 init repo with models, helpers, etc

backend/src/main/java/fr/openent/appointments/controller/CommunicationController.java, backend/src/main/java/fr/openent/appointments/controller/GridController.java, backend/src/main/java/fr/openent/appointments/core/constants/Fields.java, backend/src/main/java/fr/openent/appointments/repository/GridRepository.java, backend/src/main/java/fr/openent/appointments/repository/impl/DefaultGridRepository.java, backend/src/main/java/fr/openent/appointments/service/GridService.java, backend/src/main/java/fr/openent/appointments/service/impl/DefaultGridService.java, frontend/docker-compose.yml, frontend/src/containers/GridModal/index.tsx, frontend/src/hooks/types.ts, frontend/src/hooks/useBlurGridInputs.ts, frontend/src/hooks/useUpdateGridInputs.ts, frontend/src/providers/GridModalProvider/index.tsx, frontend/src/providers/GridModalProvider/types.ts, frontend/src/providers/GridModalProvider/utils.ts, frontend/src/services/api/communication.service.ts, frontend/src/services/api/grid.service.ts
fix creation of grid with addind security
[RDV-23](https://jira.support-ent.fr/browse/RDV-23)
=> fix: #RDV-23 fix creation of grid with addind security

backend/deployment/appointments/conf.json.template, backend/src/main/java/fr/openent/appointments/Appointments.java, backend/src/main/java/fr/openent/appointments/config/AppConfig.java, backend/src/main/java/fr/openent/appointments/core/constants/Fields.java, backend/src/main/java/fr/openent/appointments/cron/ClosingCron.java, backend/src/main/java/fr/openent/appointments/repository/GridRepository.java, backend/src/main/java/fr/openent/appointments/repository/impl/DefaultGridRepository.java, backend/src/main/java/fr/openent/appointments/service/GridService.java, backend/src/main/java/fr/openent/appointments/service/ServiceFactory.java, backend/src/main/java/fr/openent/appointments/service/impl/DefaultGridService.java
Add CRON to close all grids having an end date already passed
RDV-36 : https://jira.support-ent.fr/browse/RDV-36
=> feat(cron): [RDV-26] add CRON to close passed grids

backend/src/main/resources/sql/001-init-tables.sql
change target_public_list_id size in db 
[RDV-22](https://jira.support-ent.fr/browse/RDV-22)
=> fix: #RDV-22 fix target_public_list_id size in db

backend/src/main/java/fr/openent/appointments/model/MinimalGrid.java
fix dates
[RDV-24](https://jira.support-ent.fr/browse/RDV-24)
=> fix: #RDV-24 fix dates

frontend/src/components/GridCard/index.tsx, frontend/src/containers/FirstPageGridModal/index.tsx, frontend/src/hooks/useStructure.ts, frontend/src/providers/GlobalProvider/index.tsx, frontend/src/providers/GlobalProvider/types.ts, frontend/src/providers/GridModalProvider/index.tsx
fix structures fetching
[RDV-23](https://jira.support-ent.fr/browse/RDV-23)
=> fix: #RDV-23 fix structures fetching

backend/src/main/java/fr/openent/appointments/controller/CommunicationController.java, backend/src/main/java/fr/openent/appointments/core/constants/Constants.java, backend/src/main/java/fr/openent/appointments/helper/LogHelper.java, backend/src/main/java/fr/openent/appointments/model/UserAppointment.java, backend/src/main/java/fr/openent/appointments/model/database/NeoGroup.java, backend/src/main/java/fr/openent/appointments/model/database/NeoUser.java, backend/src/main/java/fr/openent/appointments/repository/CommunicationRepository.java, backend/src/main/java/fr/openent/appointments/repository/GridRepository.java, backend/src/main/java/fr/openent/appointments/repository/impl/DefaultCommunicationRepository.java, backend/src/main/java/fr/openent/appointments/repository/impl/DefaultGridRepository.java, backend/src/main/java/fr/openent/appointments/service/CommunicationService.java, backend/src/main/java/fr/openent/appointments/service/ServiceFactory.java, backend/src/main/java/fr/openent/appointments/service/impl/DefaultCommunicationService.java, backend/src/main/java/fr/openent/appointments/service/impl/DefaultGridService.java, frontend/src/services/api/communication.service.ts
First part of the ticket.
Here we create a new endpoint to retrieve infos of users the current user can communicate with.
These infos contains their :
- id
- display name
- functions (not formatted yet, coming soon)
Second PR will allow to retrieve two other piece of information.
RDV-26 : https://jira.support-ent.fr/browse/RDV-26
=> feat(get): [RDV-26] add endpoint to get users I can communicate with

frontend/src/providers/AvailabilityProvider/index.tsx
fix setGrids async issues
[RDV-25](https://jira.support-ent.fr/browse/RDV-25)
=> fix: #RDV-25 fix setGrids async issues

backend/src/main/java/fr/openent/appointments/enums/UserFunction.java, backend/src/main/java/fr/openent/appointments/enums/UserFunctionException.java, backend/src/main/java/fr/openent/appointments/helper/UserFunctionHelper.java, backend/src/main/java/fr/openent/appointments/model/database/NeoUser.java, backend/src/main/java/fr/openent/appointments/service/impl/DefaultCommunicationService.java
Follows this PR : https://github.com/OPEN-ENT-NG/appointments/pull/11
Here we formatted the users' functions into a displayable and readable text.
The rules followed for this are described in this documentation : https://confluence.support-ent.fr/pages/viewpage.action?pageId=536444929
RDV-38 : https://jira.support-ent.fr/browse/RDV-38
=> feat(neo): [#RDV-38] format neo functions for display

backend/src/main/resources/i18n/en.json, backend/src/main/resources/i18n/fr.json, frontend/src/containers/FirstPageGridModal/index.tsx, frontend/src/core/constants.ts, frontend/src/hooks/useUpdateGridInputs/index.ts, frontend/src/hooks/useUpdateGridInputs/utils.ts
We ensured that user inputs are clean by removing leading spaces, reducing multiple spaces to one, and limiting the input to 250 characters.
[RDV-23](https://jira.support-ent.fr/browse/RDV-23)
=> feat: #RDV-23 add string format and text helper

frontend/src/core/rights.ts, frontend/src/providers/GlobalProvider/index.tsx, frontend/src/providers/GlobalProvider/types.ts, frontend/src/routes/home/index.tsx, frontend/src/services/queries/index.ts
Show grid tab **only** for authorized users
Tab for users **without** manage grid right
Tab for users **with** manage grid right
[RDV-6](https://jira.support-ent.fr/browse/RDV-6)
=> feat: #RDV-6 show grid tab only for authorized users

backend/src/main/java/fr/openent/appointments/controller/CommunicationController.java, backend/src/main/java/fr/openent/appointments/core/constants/Constants.java, backend/src/main/java/fr/openent/appointments/helper/UserFunctionHelper.java, backend/src/main/java/fr/openent/appointments/repository/CommunicationRepository.java, backend/src/main/java/fr/openent/appointments/repository/impl/DefaultCommunicationRepository.java, backend/src/main/java/fr/openent/appointments/service/CommunicationService.java, backend/src/main/java/fr/openent/appointments/service/impl/DefaultCommunicationService.java, frontend/src/styles/theme.ts
fix communication functions
[RDV-26](https://jira.support-ent.fr/browse/RDV-26)
=> fix: #RDV-26 fix communication functions

backend/src/main/java/fr/openent/appointments/service/impl/DefaultCommunicationService.java, frontend/src/containers/BookAppointmentGridInfos/index.tsx, frontend/src/containers/BookAppointmentGridInfos/style.ts
[RDV-14](https://jira.support-ent.fr/browse/RDV-14)
=> fix: #RDV-14 feedback user order + css 

frontend/src/components/UserCard/index.tsx, frontend/src/containers/BookAppointmentGridInfos/index.tsx, frontend/src/containers/BookAppointmentGridInfos/style.ts, frontend/src/containers/BookAppointmentWeekSlotsDesktop/index.tsx, frontend/src/containers/BookAppointmentWeekSlotsDesktop/style.ts, frontend/src/core/constants.ts, frontend/src/styles/textStyles.ts
[RDV-29](https://jira.support-ent.fr/browse/RDV-29)
=> fix: #RDV-29 make feedback css

frontend/src/containers/BookAppointmentModal/index.tsx, frontend/src/containers/BookAppointmentWeekSlotsDesktop/index.tsx, frontend/src/containers/BookAppointmentWeekSlotsDesktop/style.ts, frontend/src/containers/BookAppointmentWeekSlotsMobile/index.tsx, frontend/src/containers/BookAppointmentWeekSlotsMobile/style.ts, frontend/src/providers/BookAppointmentModalProvider/index.tsx, frontend/src/providers/BookAppointmentModalProvider/types.ts, frontend/src/providers/FindAppointmentsProvider/index.tsx, frontend/src/providers/FindAppointmentsProvider/types.ts, frontend/src/routes/home/index.tsx, frontend/src/services/api/GridService/index.ts
[RDV-30](https://jira.support-ent.fr/browse/RDV-30)
=> fix: #RDV-30 make feedback

backend/src/main/java/fr/openent/appointments/core/constants/Constants.java, backend/src/main/java/fr/openent/appointments/enums/UserFunction.java, backend/src/main/java/fr/openent/appointments/helper/UserFunctionHelper.java, backend/src/main/java/fr/openent/appointments/model/database/NeoUser.java, backend/src/main/java/fr/openent/appointments/repository/impl/DefaultCommunicationRepository.java, frontend/src/components/UserCard/index.tsx, frontend/src/containers/BookAppointmentGridInfos/index.tsx, frontend/src/containers/BookAppointmentGridInfos/style.ts, frontend/src/providers/BookAppointmentModalProvider/index.tsx, frontend/src/services/api/CommunicationService/types.ts
[RDV-46](https://jira.support-ent.fr/browse/RDV-46)
=> fix: #RDV-46 make feedback

backend/src/main/java/fr/openent/appointments/controller/AppointmentController.java, backend/src/main/java/fr/openent/appointments/core/constants/Constants.java, backend/src/main/java/fr/openent/appointments/enums/HttpStatus.java, backend/src/main/java/fr/openent/appointments/exceptions/CustomException.java, backend/src/main/java/fr/openent/appointments/exceptions/ErrorCreateAppointmentException.java, backend/src/main/java/fr/openent/appointments/helper/ErrorHelper.java, backend/src/main/java/fr/openent/appointments/service/impl/DefaultGridService.java
This PR introduces a custom exception mechanism designed to enhance error management and improve the clarity of error messages provided to the frontend. By implementing this feature, we ensure a more precise and user-friendly error-handling process across the application.  
1. **Custom Exception Class**  
- A dedicated exception class encapsulates two essential attributes:  
- **Error Code**: Represents the specific type of error.  
- **Error Message**: Provides a detailed and meaningful description of the issue.  
2. **Error Helper**  
- A utility designed to centralize the handling of custom exceptions.  
- Facilitates consistent responses to the frontend by encapsulating the error code and error message in a standardized format.  
- **Improved Error Management**: Centralizing error …
=> feat: add custom exception system

backend/src/main/java/fr/openent/appointments/controller/AppointmentController.java, backend/src/main/java/fr/openent/appointments/core/constants/Constants.java, backend/src/main/java/fr/openent/appointments/model/database/AppointmentWithInfos.java, backend/src/main/java/fr/openent/appointments/model/response/ListAppointmentsResponse.java, backend/src/main/java/fr/openent/appointments/model/response/MinimalAppointment.java, backend/src/main/java/fr/openent/appointments/repository/AppointmentRepository.java, backend/src/main/java/fr/openent/appointments/repository/CommunicationRepository.java, backend/src/main/java/fr/openent/appointments/repository/impl/DefaultAppointmentRepository.java, backend/src/main/java/fr/openent/appointments/repository/impl/DefaultCommunicationRepository.java, backend/src/main/java/fr/openent/appointments/service/AppointmentService.java, backend/src/main/java/fr/openent/appointments/service/impl/DefaultAppointmentService.java
add endpoint to get my appointments
[RDV-31](https://jira.support-ent.fr/browse/RDV-31)
=> feat: #RDV-31 get my appointments

backend/src/main/java/fr/openent/appointments/controller/AppointmentController.java, backend/src/main/java/fr/openent/appointments/core/constants/Constants.java, backend/src/main/java/fr/openent/appointments/repository/AppointmentRepository.java, backend/src/main/java/fr/openent/appointments/repository/impl/DefaultAppointmentRepository.java, backend/src/main/java/fr/openent/appointments/service/AppointmentService.java, backend/src/main/java/fr/openent/appointments/service/impl/DefaultAppointmentService.java
add endpoint to get a specific appointment by its id (only if connected user is linked to the appointment)
[RDV-21](https://jira.support-ent.fr/browse/RDV-21)
=> feat: #RDV-21 get specific appointment

backend/src/main/java/fr/openent/appointments/controller/AppointmentController.java, backend/src/main/java/fr/openent/appointments/repository/AppointmentRepository.java, backend/src/main/java/fr/openent/appointments/repository/impl/DefaultAppointmentRepository.java, backend/src/main/java/fr/openent/appointments/service/AppointmentService.java, backend/src/main/java/fr/openent/appointments/service/impl/DefaultAppointmentService.java
add 2 endpoints to accept or reject an appointment
[RDV-19](https://jira.support-ent.fr/browse/RDV-19)
=> feat: #RDV-19 accept/reject appointment

backend/src/main/java/fr/openent/appointments/controller/AppointmentController.java, backend/src/main/java/fr/openent/appointments/service/AppointmentService.java, backend/src/main/java/fr/openent/appointments/service/impl/DefaultAppointmentService.java
add endpoint to cancel an appointment
[RDV-20](https://jira.support-ent.fr/browse/RDV-20)
=> feat: #RDV-20 cancel an appointment

backend/src/main/java/fr/openent/appointments/controller/AppointmentController.java, backend/src/main/java/fr/openent/appointments/model/response/AppointmentResponse.java, backend/src/main/java/fr/openent/appointments/repository/impl/DefaultAppointmentRepository.java, backend/src/main/java/fr/openent/appointments/service/AppointmentService.java, backend/src/main/java/fr/openent/appointments/service/impl/DefaultAppointmentService.java
add missing fields for endpoints get all my appointments and get a specific appointment
[RDV-31](https://jira.support-ent.fr/browse/RDV-31)
[RDV-21](https://jira.support-ent.fr/browse/RDV-21)
=> fix: #RDV-31 #RDV-21 add missing fields

backend/src/main/resources/i18n/en.json, backend/src/main/resources/i18n/fr.json, frontend/src/components/AppointmentCard/index.tsx, frontend/src/components/UserCard/index.tsx, frontend/src/components/UserPicture/index.tsx, frontend/src/components/UserPicture/types.ts, frontend/src/containers/AppointmentCardList/style.ts, frontend/src/containers/AppointmentInfosModal/index.tsx, frontend/src/containers/AppointmentInfosModal/style.ts, frontend/src/containers/AppointmentInfosModal/types.ts, frontend/src/containers/BookAppointmentGridInfos/index.tsx, frontend/src/containers/BookAppointmentGridInfos/style.ts, frontend/src/containers/MyAppointments/index.tsx, frontend/src/core/constants.ts, frontend/src/services/api/AppointmentService/types.ts
Add modal to have specific infos of an appointment
[RDV-21](https://jira.support-ent.fr/browse/RDV-21)
=> feat: #RDV-21 add appointment modal

backend/src/main/java/fr/openent/appointments/controller/AppointmentController.java, backend/src/main/java/fr/openent/appointments/core/constants/Notif.java, backend/src/main/java/fr/openent/appointments/service/AppointmentService.java, backend/src/main/java/fr/openent/appointments/service/NotifyService.java, backend/src/main/java/fr/openent/appointments/service/ServiceFactory.java, backend/src/main/java/fr/openent/appointments/service/impl/DefaultAppointmentService.java, backend/src/main/java/fr/openent/appointments/service/impl/DefaultNotifyService.java, backend/src/main/resources/i18n/timeline/en.json, backend/src/main/resources/i18n/timeline/fr.json, backend/src/main/resources/view-src/notify/accept_request_notification.html, backend/src/main/resources/view-src/notify/accept_request_notification.json, backend/src/main/resources/view-src/notify/cancel_appointment_notification.html, backend/src/main/resources/view-src/notify/cancel_appointment_notification.json, backend/src/main/resources/view-src/notify/cancel_request_notification.html, backend/src/main/resources/view-src/notify/cancel_request_notification.json, backend/src/main/resources/view-src/notify/reject_request_notification.html, backend/src/main/resources/view-src/notify/reject_request_notification.json
Implemented notifications for:
1. Accepted appointment request
2. Refused appointment request
3. Canceled appointment request
4. Canceled validated appointment
[RDV-19](https://jira.support-ent.fr/browse/RDV-19)
[RDV-20](https://jira.support-ent.fr/browse/RDV-20)
=> feat: #RDV-19 #RDV-20 make notifications

backend/src/main/java/fr/openent/appointments/controller/AppointmentController.java, backend/src/main/java/fr/openent/appointments/core/constants/Fields.java
add new endpoint to get special infos of an appointement for front appointment (from notif) display
=> feat: add new endpoint to get special infos of an appointement

frontend/src/containers/AppointmentInfosModal/index.tsx
[RDV-33](https://jira.support-ent.fr/browse/RDV-33)
=> fix: #RDV-33 style

backend/deployment/appointments/conf.json.template, backend/src/main/java/fr/openent/appointments/config/AppConfig.java, backend/src/main/java/fr/openent/appointments/controller/GridController.java, backend/src/main/java/fr/openent/appointments/core/constants/Constants.java, backend/src/main/java/fr/openent/appointments/repository/impl/DefaultTimeSlotRepository.java, backend/src/main/java/fr/openent/appointments/service/GridService.java, backend/src/main/java/fr/openent/appointments/service/impl/DefaultAppointmentService.java, backend/src/main/java/fr/openent/appointments/service/impl/DefaultGridService.java
=> fix: add cancel appointment time limit and fix minimal grids

backend/src/main/resources/i18n/en.json, backend/src/main/resources/i18n/fr.json, frontend/src/components/CustomDateCalendar/index.tsx, frontend/src/components/CustomDateCalendar/style.ts, frontend/src/components/UserCard/index.tsx, frontend/src/containers/AppointmentInfosModal/index.tsx, frontend/src/containers/AppointmentInfosModal/style.ts, frontend/src/containers/BookAppointmentGridInfos/index.tsx, frontend/src/containers/BookAppointmentGridInfos/style.ts, frontend/src/containers/BookAppointmentWeekSlotsDesktop/style.ts, frontend/src/providers/MyAppointmentsProvider/index.tsx
=> fix: make feedback of design and modals bug

frontend/eslint.config.js, frontend/package.json, frontend/src/components/AppointmentCard/index.tsx, frontend/src/components/DailySlot/index.tsx, frontend/src/components/WeekSlots/index.tsx, frontend/src/containers/AppointmentCardList/index.tsx, frontend/src/containers/MyAvailability/index.tsx, frontend/src/hooks/useUpdateGridInputs/index.ts, frontend/src/main.tsx, frontend/src/providers/AvailabilityProvider/index.tsx, frontend/src/providers/BookAppointmentModalProvider/index.tsx, frontend/src/providers/FindAppointmentsProvider/index.tsx, frontend/src/providers/GlobalProvider/index.tsx, frontend/src/providers/GridModalProvider/index.tsx, frontend/src/providers/MyAppointmentsProvider/index.tsx, frontend/src/routes/home/index.tsx, frontend/tsconfig.app.json
[RDV-](https://jira.support-ent.fr/browse/RDV-)
=> fix: eslint tests

backend/src/main/java/fr/openent/appointments/controller/AppointmentController.java, backend/src/main/java/fr/openent/appointments/controller/CommunicationController.java, backend/src/main/java/fr/openent/appointments/controller/GridController.java, backend/src/main/java/fr/openent/appointments/repository/GridRepository.java, backend/src/main/java/fr/openent/appointments/repository/impl/DefaultGridRepository.java, backend/src/main/java/fr/openent/appointments/service/GridService.java, backend/src/main/java/fr/openent/appointments/service/impl/DefaultGridService.java, backend/src/main/resources/sql/001-init-tables.sql
add endpoint to update some fields of a grid (name, color, place, videolink, publicCom)
[RDV-8](https://jira.support-ent.fr/browse/RDV-8)
=> feat(grids): #RDV-8 add endpoint to update a grid

backend/src/main/java/fr/openent/appointments/controller/AppointmentController.java, backend/src/main/java/fr/openent/appointments/controller/CommunicationController.java, backend/src/main/java/fr/openent/appointments/controller/GridController.java, backend/src/main/java/fr/openent/appointments/controller/TimeSlotController.java, backend/src/main/java/fr/openent/appointments/helper/ParamHelper.java
=> feat: add param helper

backend/src/main/java/fr/openent/appointments/controller/GridController.java, backend/src/main/java/fr/openent/appointments/core/constants/Notif.java, backend/src/main/java/fr/openent/appointments/repository/AppointmentRepository.java, backend/src/main/java/fr/openent/appointments/repository/GridRepository.java, backend/src/main/java/fr/openent/appointments/repository/impl/DefaultAppointmentRepository.java, backend/src/main/java/fr/openent/appointments/repository/impl/DefaultGridRepository.java, backend/src/main/java/fr/openent/appointments/service/AppointmentService.java, backend/src/main/java/fr/openent/appointments/service/GridService.java, backend/src/main/java/fr/openent/appointments/service/NotifyService.java, backend/src/main/java/fr/openent/appointments/service/ServiceFactory.java, backend/src/main/java/fr/openent/appointments/service/impl/DefaultAppointmentService.java, backend/src/main/java/fr/openent/appointments/service/impl/DefaultGridService.java, backend/src/main/java/fr/openent/appointments/service/impl/DefaultNotifyService.java, backend/src/main/resources/i18n/timeline/en.json, backend/src/main/resources/i18n/timeline/fr.json, backend/src/main/resources/view-src/notify/update_grid_notification.html, backend/src/main/resources/view-src/notify/update_grid_notification.json
send notifications to users impacted by grid changes
[RDV-8](https://jira.support-ent.fr/browse/RDV-8)
[RDV-9](https://jira.support-ent.fr/browse/RDV-9)
[RDV-10](https://jira.support-ent.fr/browse/RDV-10)
=> feat(notifs): #RDV-8 #RDV-9 #RDV-10 send notifications to users impacted by grid changes

backend/src/main/resources/i18n/en.json, backend/src/main/resources/i18n/fr.json, frontend/src/components/ColorPicker/index.tsx, frontend/src/components/ColorPicker/style.ts, frontend/src/components/ColorPicker/types.ts, frontend/src/components/GridCard/index.tsx, frontend/src/components/WeekSlots/index.tsx, frontend/src/containers/GridModal/index.tsx, frontend/src/core/constants.ts, frontend/src/providers/AvailabilityProvider/index.tsx, frontend/src/providers/GridModalProvider/index.tsx
[RDV-12](https://jira.support-ent.fr/browse/RDV-12)
=> feat(grids): #RDV-12 consult passed grid

backend/src/main/java/fr/openent/appointments/Appointments.java, backend/src/main/java/fr/openent/appointments/controller/MainController.java, backend/src/main/java/fr/openent/appointments/core/constants/Constants.java, backend/src/main/resources/i18n/en.json, backend/src/main/resources/i18n/fr.json, frontend/index.html, frontend/src/components/AppointmentCard/index.tsx, frontend/src/components/AppointmentCard/style.ts, frontend/src/components/AppointmentCard/types.ts, frontend/src/containers/AppointmentInfosModal/index.tsx, frontend/src/core/constants.ts, frontend/src/providers/GlobalProvider/index.tsx, frontend/src/providers/GlobalProvider/types.ts
[RDV-55](https://jira.support-ent.fr/browse/RDV-55)
=> feat: #RDV-55 add config to front

frontend/src/components/AppointmentCard/index.tsx, frontend/src/containers/AppointmentInfosModal/index.tsx, frontend/src/containers/BookAppointmentWeekSlotsDesktop/index.tsx, frontend/src/containers/BookAppointmentWeekSlotsMobile/index.tsx, frontend/src/core/models/Time/index.ts, frontend/src/core/utils.ts, frontend/src/main.tsx, frontend/src/providers/BookAppointmentModalProvider/index.tsx, frontend/src/providers/BookAppointmentModalProvider/utils.ts
[RDV-56](https://jira.support-ent.fr/browse/RDV-56)
=> fix(dayjs): #RDV-56 fix issue of date format

backend/deployment/appointments/conf.json.template, backend/src/main/java/fr/openent/appointments/config/AppConfig.java, backend/src/main/java/fr/openent/appointments/controller/MainController.java, backend/src/main/java/fr/openent/appointments/core/constants/Constants.java, frontend/index.html, frontend/src/core/constants.ts, frontend/src/main.tsx, frontend/src/providers/GlobalProvider/index.tsx, frontend/src/providers/GlobalProvider/types.ts
This pull request introduces a new configuration option for theme customization and refactors how the minimum hours before cancellation is handled. The changes span across backend configuration, frontend data handling, and constants management.
* Added `theme-platform` configuration in `conf.json.template` and integrated it into `AppConfig` class. 
* Updated `MainController` to include `themePlatform` in the parameters passed to the frontend. 
* Added `CAMEL_THEME_PLATFORM` and `KEBAB_THEME_PLATFORM` constants in `Constants.java`. 
* Refactored `index.html` to include `themePlatform` and `minHoursBeforeCancellation` as data attributes on the root element. 
* Introduced `DEFAULT_THEME` constant and updated imports in `main.tsx`. 
* Updated `main.tsx` to read `themePlatform` and …
=> feat(theme): #RDV-51 add theme conf value used to apply the cgi theme

backend/src/main/java/fr/openent/appointments/service/impl/DefaultAppointmentService.java, backend/src/main/java/fr/openent/appointments/service/impl/DefaultGridService.java, backend/src/main/resources/i18n/en.json, backend/src/main/resources/i18n/fr.json, frontend/src/components/AppointmentCard/style.ts, frontend/src/components/WeekSlots/index.tsx, frontend/src/components/WeekSlots/style.ts, frontend/src/containers/AppointmentInfosModal/index.tsx, frontend/src/containers/AppointmentInfosModal/style.ts, frontend/src/containers/BookAppointmentModal/index.tsx, frontend/src/containers/BookAppointmentModal/style.ts, frontend/src/containers/FirstPageGridModal/index.tsx, frontend/src/containers/GridModal/index.tsx, frontend/src/core/constants.ts, frontend/src/core/enums.ts, frontend/src/hooks/types.ts, frontend/src/hooks/useBlurGridInputs.ts, frontend/src/hooks/useUpdateGridInputs/index.ts, frontend/src/providers/AvailabilityProvider/index.tsx, frontend/src/providers/GridModalProvider/index.tsx, frontend/src/providers/GridModalProvider/types.ts, frontend/src/providers/GridModalProvider/useFiles.ts, frontend/src/providers/GridModalProvider/utils.ts
This pull request includes several changes across both the backend and frontend of the application, focusing on improving functionality and user experience. The most important changes include modifications to appointment handling logic, updates to the i18n files for better localization, and enhancements to the frontend components for better UI consistency and accessibility.
* [`DefaultAppointmentService.java`](diffhunk://#diff-f78821c0ba4749ac878a95ec7d8234cb6a4588e3a4df41a38ac167ea8a5d0cc1L176-R176): Fixed an issue where the wrong user ID was being used to fetch document responses and improved the handling of appointment state changes. [[1]](diffhunk://#diff-f78821c0ba4749ac878a95ec7d8234cb6a4588e3a4df41a38ac167ea8a5d0cc1L176-R176) …
=> fix: #RDV-58 fix some front and back issues

backend/src/main/resources/view-src/notify/accept_request_notification.html, backend/src/main/resources/view-src/notify/cancel_appointment_notification.html, backend/src/main/resources/view-src/notify/cancel_request_notification.html, backend/src/main/resources/view-src/notify/reject_request_notification.html, backend/src/main/resources/view-src/notify/update_grid_notification.html, frontend/index.html, frontend/src/components/GridCard/index.tsx, frontend/src/containers/AppointmentCardList/index.tsx, frontend/src/containers/AppointmentInfosModal/index.tsx, frontend/src/containers/AppointmentInfosModal/style.ts, frontend/src/containers/BookAppointmentGridInfos/index.tsx, frontend/src/containers/BookAppointmentGridInfos/style.ts, frontend/src/containers/FindAppointments/index.tsx, frontend/src/containers/FirstPageGridModal/index.tsx, frontend/src/containers/GridList/index.tsx, frontend/src/containers/MyAppointments/index.tsx, frontend/src/main.tsx, frontend/src/providers/AvailabilityProvider/index.tsx, frontend/src/styles/theme.ts
This pull request includes multiple changes to both the frontend and backend components of the application, focusing on improving the user interface and enhancing internationalization support. The most important changes are listed below:
* **HTML Notifications:**
* Consolidated `{{/userUri}}` and `{{^userUri}}` blocks in notification templates to simplify the structure in `accept_request_notification.html`, `cancel_appointment_notification.html`, `cancel_request_notification.html`, and `reject_request_notification.html`. [[1]](diffhunk://#diff-ccd50c978189024b7c4a28f0991fc3b0b942c1c891c80fab0d88ba578ba9c954L6-R13) [[2]](diffhunk://#diff-4847b1c7cb87dca445c5fd863ea14e511904fe4279086c5719e7e0df26dfad40L7-R14) [[3]](diffhunk://#diff-0c448ea07fd1ff445df3952f14f3c54c95a0b2add341f1aca231f9040f11 …
=> fix(style): #RDV-59 fix some feedback of style from RC

frontend/src/containers/AppointmentInfosModal/index.tsx, frontend/src/containers/AppointmentInfosModal/style.ts, frontend/src/containers/BookAppointmentGridInfos/index.tsx, frontend/src/containers/FirstPageGridModal/index.tsx, frontend/src/containers/GridModal/index.tsx
This pull request includes several changes to improve the user interface and functionality of various modal components in the frontend. The most important changes involve updating the styling of elements, adding new hooks for better state management, and enhancing the user experience by ensuring elements are properly displayed and scrollable.
* [`frontend/src/containers/AppointmentInfosModal/index.tsx`](diffhunk://#diff-a1d10e2fc940538bb667578b02eef98cd028ac6f7604f20246590dc270e38085L109-R117): Replaced `EllipsisWithTooltip` with `Typography` for the `videoCallLink` to ensure proper word wrapping and breaking.
* [`frontend/src/containers/AppointmentInfosModal/style.ts`](diffhunk://#diff-5ef809d200fc2ccb9018c76851f6aaaa710edacf46dd121b6fcdc28876351f00L6-R7): Adjusted the modal and user …
=> fix: #RDV-59 make style feedback

backend/src/main/java/fr/openent/appointments/model/payload/GridPayload.java, frontend/src/components/CustomDateCalendar/index.tsx, frontend/src/components/CustomDateCalendar/utils.ts, frontend/src/components/DailySlot/utils.ts, frontend/src/components/RangeDatePicker/index.tsx, frontend/src/containers/AppointmentInfosModal/index.tsx, frontend/src/core/dayjs.const.ts, frontend/src/core/models/Time/index.ts, frontend/src/core/utils.ts, frontend/src/providers/BookAppointmentModalProvider/index.tsx, frontend/src/providers/BookAppointmentModalProvider/utils.ts
This pull request includes several changes to both the backend and frontend code to improve date handling and validation for the `RangeDatePicker` component and the `GridPayload` model. The most important changes include adding new date validation logic and updating the component behavior to handle these validations.
* [`backend/src/main/java/fr/openent/appointments/model/payload/GridPayload.java`](diffhunk://#diff-2cb8c7a4ced3a54d0c54968c43363ef0bfa4a0428c110ef47dcf47e30d9301e3R199): Added a validation check to ensure that `endDate` is within one year of `beginDate` in the `isValid` method.
* `frontend/src/components/RangeDatePicker/index.tsx`: 
- Imported `useEffect` to handle side effects.
- Added an effect to reset `endDate` if it is more than one year after `startDate`.
- Updated the …
=> feat(grid): #RDV-59 add grid limit duration of 1yo

JenkinsFile, backend/src/main/java/fr/openent/appointments/repository/impl/DefaultCommunicationRepository.java
This pull request includes a small change to the `JenkinsFile`. The change adds a command to remove the `view` directory in the `src/main/resources/` path before creating it again.
* [`JenkinsFile`](diffhunk://#diff-455fd99a893bc3b67e59b381f83a22aa10caf4a751c2b87729959635e35d6f99R28): Added a command to remove the `view` directory in the `src/main/resources/` path before creating it again to ensure a clean state.
[RDV-70](https://jira.support-ent.fr/browse/RDV-70)
=> fix(notifs): #RDV-70 fix jenkinsFile

frontend/package.json
This pull request includes updates to the `frontend/package.json` file to specify fixed versions for several dependencies instead of using the "develop" branch.
Dependency updates:
* Updated `@cgi-learning-hub/icons` from "develop" to "1.5.0".
* Updated `@cgi-learning-hub/theme` from "develop" to "1.5.0".
* Updated `@cgi-learning-hub/ui` from "develop" to "1.5.0".
* Updated `@edifice.io/react` from "2.0.2" to "2.1.0".
[RDV-72](https://jira.support-ent.fr/browse/RDV-72)
=> fix(logo): #RDV-72 update edifice react version

backend/src/main/java/fr/openent/appointments/repository/impl/DefaultCommunicationRepository.java
This pull request updates the `getCommunicationQuery` method in the `DefaultCommunicationRepository` class to include a new match clause for retrieving users associated with groups. This change enhances the query by ensuring that user-group relationships are explicitly considered.
* [`backend/src/main/java/fr/openent/appointments/repository/impl/DefaultCommunicationRepository.java`](diffhunk://#diff-bfd913f064491b0c2a2b5c30c56632b3f52960dfc752ea24b1997725e41915fcR151): Added a `MATCH` clause to link groups to users via the `[:IN]` relationship, ensuring that user associations with groups are retrieved. [[1]](diffhunk://#diff-bfd913f064491b0c2a2b5c30c56632b3f52960dfc752ea24b1997725e41915fcR151) [[2]](diffhunk://#diff-bfd913f064491b0c2a2b5c30c56632b3f52960dfc752ea24b1997725e41915fcR168)
=> fix(groups): filter empty groups

frontend/package.json, frontend/src/hooks/useTheme.ts, frontend/src/main.tsx
Add theme support for 1d 
[RDV-85](https://jira.support-ent.fr/browse/RDV-85)
=> feat(theme): #RDV-85 add 1D theme support on appointments
